name:                WCET
version:             0.1.0.0
github:              "HampusBalldin/WCET"
license:             BSD3
author:              "Hampus Balldin"
maintainer:          "hampus.balldin@gmail.com"
copyright:           "Copyright 2018 (C)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HampusBalldin/WCET#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - mtl
    - transformers
    - QuickCheck


executables:
  WCET-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WCET
    - containers
    - mtl
    - transformers

tests:
  WCET-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WCET
